# python設定
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = 'python'
#
#[[plugins]]
#repo = 'lambdalisue/vim-pyenv'
#depends = 'davidhalter/jedi-vim'
#on_ft = 'python'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = 'python'

# C#
[[plugins]]
repo = 'OrangeT/vim-csharp'
on_ft = ['cs','csi','csx']

# JavaScript
[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'js'

[[plugins]]
repo = 'myhere/vim-nodejs-complete'
on_ft = 'js'

[[plugins]]
repo = 'teramako/jscomplete-vim'
on_ft = 'js'

# html5
[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = 'html'

# css3
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

# 一般設定
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

