# python設定

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
depends = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = 'python'


# C#

[[plugins]]
repo = 'OrangeT/vim-csharp'
on_ft = ['cs','csi','csx']

# 一般設定

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

