add_newline = true

format = """------------------------
$gcloud
$aws
$kubernetes\
$golang\
$python\
$rust\
$nodejs
$time$directory$git_branch$git_commit$git_status
$shell$status$character"""

[package]
disabled = true

[character]
success_symbol = "[>>>](bold green)"
error_symbol = "[✗✗✗](bold red)"
vicmd_symbol = "[V](bold green)"

[git_branch]
symbol = "🌱 "

[kubernetes]
disabled = false
format = '[$symbol$context\($namespace\)](green)'

[gcloud]
disabled = false
symbol = "gcloud:"
format = '[$symbol$account(@domain)(\($project\))$region](cyan)'
[gcloud.region_aliases]
us-central1 = "uc1"
asia-northeast1 = "an1"

[aws]
disabled = false
symbol = "aws:"
format = '[$symbol$profile$region]($style)'

[time]
disabled = false
format = '[$time]($style) '

[golang]
disabled=false
symbol = "go:"
format = '[$symbol$version](bold cyan)'

[python]
disabled=false
symbol = "py:"
format = '[$symbol$pyenv_prefix\($version\)\($virtualenv\)]($style)'
python_binary = ["./venv/bin/python", "python", "python3"]

[rust]
disabled=false
symbol="rs:"
format = "[$symbol$version](red bold)"

[nodejs]
disabled=false
symbol="node:"
format = "[$symbol($version)]($style)"

[shell]
disabled=true
format = "[$indicator](bold green)"
