add_newline = true

format = """
------------------------
$time$directory$git_branch$git_commit$git_status
$kubernetes
$gcloud
$status$character"""

[package]
disabled = true

[character]
success_symbol = "[>>>](bold green)"
error_symbol = "[✗✗✗](bold red)"
vicmd_symbol = "[V](bold green)"

[git_branch]
symbol = "🌱 " 

[kubernetes]
disabled = false
format = '[$symbol$context\($namespace\)](green)'

[gcloud]
disabled = false 
format = '[$symbol$account(\($project\))$region](blue)'

[aws]
disabled = false
symbol = "🅰 "
format = '[$symbol$profile$region]($style)'

[time]
disabled = false
format = '[$time]($style) '
